name: Pull request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: action/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: 'postgres'
          envkey_POSTGRES_PASSWORD: 'postgres'
          envkey_POSTGRES_DB: 'students__test'
          envkey_DATABASE_URL: 'postgresql://postgres:postgres@db_postgres_students:5432/students__tests'
          directory: back-end/
          file_name: .env.test
          fail_on_empty: true
      - name: Run tests
        run: docker-compose -f back-end/docker-compose-test.yml run student_selector_api npm run test
